apiVersion: v1
kind: Namespace
metadata:
  name: ns-demo-app
  labels:
    name: demo-app

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: ns-demo-app
  labels:
    app: demo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-app
  strategy: {}
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - image: nginx:1.14.2
        name: nginx
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi

---

apiVersion: v1
kind: Service
metadata:
  name: svc-demo-app
  namespace: ns-demo-app
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'
    service.beta.kubernetes.io/aws-load-balancer-security-groups: ""
spec:
  selector:
    app: demo-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
